spring:
  # 多环境配置，默认dev
  profiles:
    active: dev
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


#日志
logging:
  config: classpath:config/logback-spring.xml
  file:
    path: /home/data/logs/tyblog





